slug: action
name_fr: Action
name_en: Action
description_fr: Pour intervenir. Vous avez besoin d'une action, d'une INTERVENTION pour vous, votre équipe ou votre collectif ? Vous voulez prendre soin de la relation, améliorer sa performance, travailler l'intelligence collective ou tout simplement travailler sur vos challenges personnels ?
description_en: To intervene. Do you need an action, an INTERVENTION for yourself, your team or your group? Do you want to care for relationships, improve their performance, work on collective intelligence or simply work on your personal challenges?
icon: bolt
order: 3
