slug: action
name_fr: Action
name_en: Action
description_fr: Accompagnement d’équipes, d’organisations et de dirigeants et managers sous forme de conseil, coaching et formations
description_en: Accompagnement d’équipes, d’organisations et de dirigeants et managers sous forme de conseil, coaching et formations
icon: bolt
order: 3
