slug: action
name_fr: Action
name_en: Action
description_fr: Accompagnement d’équipes, d’organizations et de dirigeants et managers sous forme de conseil, coaching et formations
description_en: Support for teams, organizations and managers and leaders through consulting, coaching and training
icon: bolt
order: 3
